@include FL_Dev.ini

[DACOM]
IgnoreDACOMEnv = true
DllPath = .\

[Libraries]
readfile.dll
engbase.dll
x86math.dll
rendcomp.dll
system.dll
Thorn.dll
DebugLib.dll
rp8.dll
shading.dll
MultiCruise.dll
RandomDamage.dll
chklootvol.dll
healing.dll
EquipMass.dll
;EquipDrag.dll
RandomJumps.dll
ShipRange.dll
ammolimit.dll
GroupMine.dll
moors.dll
JumpOutPt.dll
ChatRepSrv.dll
FLSharp.dll

[System]
DirectX8
MaterialLibrary
TextureLibrary

[Engine]
Animation
Hardpoint
RenderManager

[RenderManager]
SphereMesh
TriMesh